// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW95LXyCQLCH-gG15W6hLT1lhEisQsFjo',
    appId: '1:305628683462:web:4f1665fbc4478951920bc7',
    messagingSenderId: '305628683462',
    projectId: 'safelinkgsu',
    authDomain: 'safelinkgsu.firebaseapp.com',
    storageBucket: 'safelinkgsu.firebasestorage.app',
    measurementId: 'G-7C2X4ES2FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5_zE8Ushi_ULpddExd2G-Wt7q8j6_2g',
    appId: '1:305628683462:android:0aba966993f5f19a920bc7',
    messagingSenderId: '305628683462',
    projectId: 'safelinkgsu',
    storageBucket: 'safelinkgsu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Er95vChr4wIOtI_cdCNeh3f3fIHk7c',
    appId: '1:305628683462:ios:6d2574ab5a9c39ef920bc7',
    messagingSenderId: '305628683462',
    projectId: 'safelinkgsu',
    storageBucket: 'safelinkgsu.firebasestorage.app',
    iosBundleId: 'com.example.safelinkgsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Er95vChr4wIOtI_cdCNeh3f3fIHk7c',
    appId: '1:305628683462:ios:6d2574ab5a9c39ef920bc7',
    messagingSenderId: '305628683462',
    projectId: 'safelinkgsu',
    storageBucket: 'safelinkgsu.firebasestorage.app',
    iosBundleId: 'com.example.safelinkgsu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW95LXyCQLCH-gG15W6hLT1lhEisQsFjo',
    appId: '1:305628683462:web:c492232170574beb920bc7',
    messagingSenderId: '305628683462',
    projectId: 'safelinkgsu',
    authDomain: 'safelinkgsu.firebaseapp.com',
    storageBucket: 'safelinkgsu.firebasestorage.app',
    measurementId: 'G-GMJ4G8ZRGH',
  );
}
